### PR TITLE
Fix TypeScript Definitions

### PR DESCRIPTION
**Pull request by 67726e**
Alright, I may have gone a bit overboard here... but here is a pull request:

- Fix the Malformed Definitions per Original Issue
- Add Scripts for Building TypeScript Definitions
- Add Script for Testing TypeScript Definitions
- Fix `README.md` for Missing Methods in `Jobs`
- Add `DEVELOPMENT.md` for Scripts

### CODE REVIEW

**Comment by chrismorison-wt** [comment]
Hi @67726e thanks for all your effort on this, but yes I do think you have gone a bit overboard!

While these extra scripts for auto-generating type definition files are very clever, to be honest, I'm not keen on inheriting them into what is currently very simple and stable package, particularly when I'm not expecting much (if at anything) to change in the future.

I'm also not keen on using `// @ts-ignore` to avoid TS warnings, when sources of the warnings can be fixed relatively easy.

I've pushed my own relatively simple commit which fixes all the issues you've observed, including the inconsistencies in the readme - thanks for reporting those.

**Comment by 67726e** [comment]
Well, credit where credit is due - you've updated the source and hand-written type definitions... but your so-called fix of the issues brought up via `// @ts-ignore` are not proper fixes. Rather, you're abusing the gradual typing ability of TypeScript.

Seeing as you have no interest in more broadly fixing the spaghetti code in this repository I'm going to have to consider this yet another instance of low-quality JavaScript abandonware.

Have a great week!

**Comment by wildhart** [comment]
Hi @67726e.  I'm sorry if I've upset you by not accepting your PR.

Regarding not cherry-picking from your PR - that wouldn't have been practical.  All I needed was a couple of extra `?` and two extra lines in my type definition file (which you replaced completely), and deleting a block from the readme.  All the typescript fixes (which are fixes, btw) were not in any of your commits.

None of your commits included improvements for the 'spaghetti' code, (most of which I inherited).  I haven't passed any of your own work off as my own.

As for 'abandonware', definitely not.  I replied to your initial bug report within 3 hours (5:36am my time), and would've pushed a fix same day if you hadn't volunteered to do so.  Over the same period I supported another user of this package who was having difficulty understanding how to use it.  The small number of issues on this repo are all closed and were done so very quickly.  I personally use this package in several production projects which are still under active development. So no, definitely not abandonware.

This is simple and mature package, and does it's job well.  So I don't need to spend any more time on it or overcomplicate it any than necessary for support.

Thanks again for your interest though - I really am grateful.  And I'm sure you had fun writing your scripts, but please don't take offence at my not including them in my own repo.  This is open source though - feel free to fork and publish your own package.  I hope you're still responding quickly to issues in 5 years time.

**Comment by 67726e** [comment]
> I'm sorry if I've upset you by not accepting your PR.

It's not the lack of accepting my scripts - it's your complete dishonest approach, that which makes the world a worse place. 

In my early 20s I ran into a junkie on the street-corner peddling a story about a medical incident, a hospital stay, and needing a fiver to get a bus ride home. I stopped and listened to this man's story and gave him a twenty dollar bill and wished him luck.  Two weeks later the same man was peddling the same story on the same street corner, getting money off of some tourists.

To this day, I don't look at a panhandler the same way - you just can undo the little things like that.

Here I sit, wondering why someone would just up and steal credit for someone else' work like that. If a different path was type solution desired, ask. If the scripts unnecessary, ask - they can be deleted far easier than they were created. If you're not sure how to use the tools in front of you, ask. If you're not sure how to use a tool to cherry-pick a commit, ask.

That's the beauty of open-source - folks helping other folks. 

You had that little inflection point, handle things squarely, walk the narrow path.

Instead another bastard has taken my last $20.

**Pull request closed without merging**
